import React from 'react';
import { Target, Layers, Repeat, TrendingUp, Users } from 'lucide-react';

const FrameworkGuide: React.FC = () => {
  return (
    <div className="space-y-8 animate-fadeIn pb-20">
      {/* Hero Section */}
      <div className="bg-gradient-to-r from-blue-900 to-slate-900 text-white p-8 rounded-2xl shadow-xl">
        <h1 className="text-3xl font-bold mb-4">Bridging the GTM Gap™</h1>
        <p className="text-blue-100 text-lg max-w-3xl leading-relaxed">
          The GTM Gap™ represents the critical chasm between the excitement of a product’s initial launch 
          and establishing a scalable, efficient revenue engine. We help you navigate from initial success 
          to leading world-class go-to-market operations.
        </p>
      </div>

      {/* The 4 Phases */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
        <div className="col-span-1 md:col-span-2 mb-2">
          <h2 className="text-2xl font-bold text-slate-900">The Framework Phases</h2>
          <p className="text-slate-600">A structured approach to tackle obstacles and achieve hyper-growth.</p>
        </div>

        {/* Phase 1: Stabilization */}
        <div className="bg-white p-6 rounded-xl border-l-4 border-blue-500 shadow-sm">
          <div className="flex items-center gap-3 mb-4">
            <div className="bg-blue-100 p-2 rounded-lg text-blue-600">
              <Target size={24} />
            </div>
            <h3 className="text-xl font-bold text-slate-800">1. Stabilization</h3>
          </div>
          <p className="text-slate-600 mb-4 text-sm font-medium uppercase tracking-wide">Your Launchpad for Sustainable Growth</p>
          <p className="text-slate-700 mb-4">
            Creates a solid starting point by assessing and stabilizing your current revenue function. 
            Focuses on diagnosing foundational problems and creating clarity.
          </p>
          <ul className="space-y-2 text-sm text-slate-600">
            <li className="flex items-start gap-2">
              <span className="text-blue-500 font-bold">•</span> Pipeline Integrity
            </li>
            <li className="flex items-start gap-2">
              <span className="text-blue-500 font-bold">•</span> Team Capability Alignment
            </li>
            <li className="flex items-start gap-2">
              <span className="text-blue-500 font-bold">•</span> Data-Driven Decision Making
            </li>
          </ul>
        </div>

        {/* Phase 2: Foundation */}
        <div className="bg-white p-6 rounded-xl border-l-4 border-indigo-500 shadow-sm">
          <div className="flex items-center gap-3 mb-4">
            <div className="bg-indigo-100 p-2 rounded-lg text-indigo-600">
              <Layers size={24} />
            </div>
            <h3 className="text-xl font-bold text-slate-800">2. Foundation</h3>
          </div>
          <p className="text-slate-600 mb-4 text-sm font-medium uppercase tracking-wide">Without It, the House Crumbles</p>
          <p className="text-slate-700 mb-4">
            Builds the necessary structures, processes, and teams that support sustainable growth. 
            Transforms preliminary processes into fully operational structures.
          </p>
          <ul className="space-y-2 text-sm text-slate-600">
            <li className="flex items-start gap-2">
              <span className="text-indigo-500 font-bold">•</span> Vision & Strategy Roadmap
            </li>
            <li className="flex items-start gap-2">
              <span className="text-indigo-500 font-bold">•</span> Process Implementation (SOPs)
            </li>
            <li className="flex items-start gap-2">
              <span className="text-indigo-500 font-bold">•</span> Technology & Tools Stack
            </li>
          </ul>
        </div>

        {/* Phase 3: Repeatability */}
        <div className="bg-white p-6 rounded-xl border-l-4 border-purple-500 shadow-sm">
          <div className="flex items-center gap-3 mb-4">
            <div className="bg-purple-100 p-2 rounded-lg text-purple-600">
              <Repeat size={24} />
            </div>
            <h3 className="text-xl font-bold text-slate-800">3. Repeatability</h3>
          </div>
          <p className="text-slate-600 mb-4 text-sm font-medium uppercase tracking-wide">Ensuring Sustainable Growth</p>
          <p className="text-slate-700 mb-4">
            Establishes consistent, efficient processes that can be replicated to produce predictable outcomes. 
            Ensures revenue is generated by systems, not just heroic efforts.
          </p>
          <ul className="space-y-2 text-sm text-slate-600">
            <li className="flex items-start gap-2">
              <span className="text-purple-500 font-bold">•</span> Documented Playbooks
            </li>
            <li className="flex items-start gap-2">
              <span className="text-purple-500 font-bold">•</span> Consistent Messaging
            </li>
            <li className="flex items-start gap-2">
              <span className="text-purple-500 font-bold">•</span> Feedback Loops
            </li>
          </ul>
        </div>

        {/* Phase 4: Scalability */}
        <div className="bg-white p-6 rounded-xl border-l-4 border-emerald-500 shadow-sm">
          <div className="flex items-center gap-3 mb-4">
            <div className="bg-emerald-100 p-2 rounded-lg text-emerald-600">
              <TrendingUp size={24} />
            </div>
            <h3 className="text-xl font-bold text-slate-800">4. Scalability</h3>
          </div>
          <p className="text-slate-600 mb-4 text-sm font-medium uppercase tracking-wide">The Rocket Fuel for Growth</p>
          <p className="text-slate-700 mb-4">
            Strategically expanding operations to meet increasing demand without sacrificing quality or efficiency. 
            Includes new market entry and mass talent acquisition.
          </p>
          <ul className="space-y-2 text-sm text-slate-600">
            <li className="flex items-start gap-2">
              <span className="text-emerald-500 font-bold">•</span> Strategic Market Expansion
            </li>
            <li className="flex items-start gap-2">
              <span className="text-emerald-500 font-bold">•</span> Financial Readiness
            </li>
            <li className="flex items-start gap-2">
              <span className="text-emerald-500 font-bold">•</span> Customer Experience Excellence
            </li>
          </ul>
        </div>
      </div>

      {/* Team Section */}
      <div className="bg-slate-50 p-8 rounded-xl border border-slate-200">
        <div className="flex items-center gap-3 mb-6">
          <Users className="text-slate-700" size={28} />
          <h2 className="text-2xl font-bold text-slate-900">Who We Are</h2>
        </div>
        <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
          <div>
            <h3 className="font-bold text-lg text-slate-800">Adam</h3>
            <p className="text-sm text-blue-600 font-medium mb-2">The Revenue Team Architect</p>
            <p className="text-sm text-slate-600 leading-relaxed">
              Over 15 years building and scaling high-growth B2B companies to over $100M ARR. 
              Expert in creating high-performance sales cultures and optimizing revenue processes.
            </p>
          </div>
          <div>
            <h3 className="font-bold text-lg text-slate-800">Dale</h3>
            <p className="text-sm text-blue-600 font-medium mb-2">The Global Go-to-Market Expert</p>
            <p className="text-sm text-slate-600 leading-relaxed">
              Two decades driving over $150M in revenue across six countries. 
              Specializes in international market entry and aligning product value with customer needs.
            </p>
          </div>
          <div>
            <h3 className="font-bold text-lg text-slate-800">Jake</h3>
            <p className="text-sm text-blue-600 font-medium mb-2">The Enterprise Sales Accelerator</p>
            <p className="text-sm text-slate-600 leading-relaxed">
              Proven track record catapulting startups from $1M to over $250M. 
              Expert in high-ticket B2B sales and developing elite sales training programs.
            </p>
          </div>
        </div>
      </div>
    </div>
  );
};

export default FrameworkGuide;
